version: '3.8'

services:
  bankbot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AZURE_OPENAI_KEY
      - AZURE_OPENAI_ENDPOINT
      - AZURE_OPENAI_DEPLOYMENT
      - TELEGRAM_BOT_TOKEN
    volumes:
      - /tmp:/tmp
    restart: unless-stopped 